# Generated by Django 2.0.3 on 2018-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='capacity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='kind',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
