# Generated by Django 2.0.3 on 2018-03-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180330_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
