# Generated by Django 2.0.3 on 2018-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180330_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='capacity',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
