# Generated by Django 2.0.3 on 2018-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180330_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='capacity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
