# Generated by Django 2.0.3 on 2018-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='extracted_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
