# Generated by Django 2.0.3 on 2018-03-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180330_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Unknown'), (10, 'ISRO'), (20, 'Agriculture'), (30, 'Defence'), (40, 'Telecommunications'), (50, 'IT'), (60, 'Admin')], default=0),
        ),
    ]
